-- unfortunately, i did not make this! it's an adapted version of kohl's fly script that was created all the way back in 2014.
-- it's very ... 2014 ... and lacks many features modern fly scripts have
-- it's buggy, i'll admit, more so even to the 2014 version. but it works.
